import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Header } from "./components/header-input";

const mont = Montserrat({ weight: ["300", "400", "600", "800"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mont.className}>
        <div className="flex flex-col justify-center w-[90%] m-auto">
          <Header />
          
          {children}
        </div>
      </body>
    </html>
  );
}
